### ISSUE TITLE
I am curious what it does, a working example in the documentation or video might help explain

### ISSUE THREAD

**Issue by coding-to-music** [sphinx-notes/snippet#10]
Not sure what it does? 
https://sphinx-notes.github.io/snippet/

btw your content is good if you don't mind I may include some of your pages here:
https://pandemic-overview.readthedocs.io/en/latest/

In particular stuff that works I put in here:
https://pandemic-overview.readthedocs.io/en/latest/myGuides/Advanced-Computer-Setup.html

Feel free to say hi to me
https://pandemic-overview.readthedocs.io/en/latest/Help-about/help.html

**Comment by SilverRainZ** [comment]
Hello, it is a "snippet manager" for sphinx dcoument, it index valuable snippet  and you can access them in a extremly fast speed.

Document is not complete yet, I will complete it before I make a stable release. see #1.

**Comment by SilverRainZ** [comment]
Video in https://silverrainz.me/blog/sphinx-as-note-taking-system-2.html#vim may help you understand, but it is Chinese only :'(

**Comment by SilverRainZ** [comment]
Hello @coding-to-music, I purpose to release 1.0 for this project. And document is available here: https://sphinx-notes.github.io/snippet/ , can you please take a review?
